### ISSUE TITLE
Update to virus total API v3, and research improvements this provides

### ISSUE THREAD

**Issue by tomanderson2** [Nuix/VirusTotal-Integration#2]
https://developers.virustotal.com/v3.0/reference

Virus Total says there are currently no plans to deprecate v2 API, but it should be easy enough to update.

> VT APIv3 is the preferred way to programmatically interact with VirusTotal. While older API endpoints are still available and will not be deprecated, we encourage you to migrate your workloads to this new version. It exposes far richer data in terms of: IoC relationships, sandbox dynamic analysis information, static information for files, YARA workloads management, crowdsourced detection details, etc.

I've tested this locally, and there are several useful items available like VHash, imphash and VT tags, as well as some features for premium users only that could be explored.

**Comment by JuicyDragon** [comment]
👏 thank you for taking a look into this
